vim.g.encoding = 'UTF-8'
vim.o.fileencoding = 'utf-8'
vim.wo.number = true
vim.wo.cursorline = true
vim.wo.signcolumn = 'yes'
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftround = true
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.autoindent = true
vim.o.smartindent = true
vim.o.smartcase = true
vim.o.hlsearch = true
vim.o.incsearch = true
vim.o.showcmd = true
vim.o.cmdheight = 1
vim.o.autoread = true
vim.o.hidden = true
vim.o.undofile = true
vim.o.swapfile = true
vim.o.undodir = vim.fn.stdpath('cache') .. '/undo//'
vim.o.updatetime = 300
vim.o.timeoutlen = 800
vim.o.splitbelow = true
vim.o.splitright = true
vim.opt.completeopt = { 'menu', 'menuone', 'noinsert' }
vim.o.termguicolors = true
vim.opt.termguicolors = true
vim.o.list = true
vim.opt.listchars = { tab = '›.', trail = '·', extends = '…', nbsp = '.' }
vim.o.wildmenu = true
vim.o.pumheight = 10
vim.o.showtabline = 2
vim.o.showmode = false
vim.opt.clipboard = 'unnamedplus'
vim.o.mouse = nil

vim.o.title = true
